[tools]
node = "latest"
bun = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:swagger-ui-watcher" = "latest"
"npm:aws-sdk" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
